### ISSUE TITLE
Doesn't seem to properly report failures?

### ISSUE THREAD

**Issue by drj17** [sorry-cypress/cy2#3]
Apologies if this is unrelated, but it only started happening when we switched to using cy2 in our github action.

In our integration-tests.yml file:
```
 - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn api, yarn start:test
          wait-on: 'http://localhost:3000, http://localhost:8081/cypress'
          wait-on-timeout: 120
          install: false
          group: 'E2E Tests'
          command: yarn cy2 run --parallel --record'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_API_URL: https://<app-name>.herokuapp.com
```

We have a cypress test that _is_ failing, but in github it says that all checks are passing.
![Screen Shot 2021-04-23 at 4 35 00 PM](https://user-images.githubusercontent.com/13426126/115927057-dbb04280-a451-11eb-801c-8c2c1e17e9b6.png)

![Screen Shot 2021-04-23 at 4 40 23 PM](https://user-images.githubusercontent.com/13426126/115927552-9b9d8f80-a452-11eb-8b58-7fcf5ff05954.png)
