### ISSUE TITLE
I have a problem with the parallelization: --parallel doesn't work.

### ISSUE THREAD

**Issue by KevinPusateri** [sorry-cypress/cy2#42]
I have a problem with the parallelization.
In the second Test remains pending.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/67141307/210543145-a53af474-ac2d-4985-8855-fb9261472ebe.png">

The keywork --parallel doesn't seems working.
My script -> `set CYPRESS_API_URL=http://localhost:1234/ && .\\node_modules\\.bin\\cy2 run --spec cypress/e2e/clients/mw_censimento* --record --parallel --key somekey --ci-build-id testProva`

**Comment by KevinPusateri** [comment]
i used this docker-compose.minio.yml:
```
`version: '3.6'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/data-mongo-cypress:/data/db

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/s3.driver'
      GITLAB_JOB_RETRIES: 'false'
      AWS_ACCESS_KEY_ID: 'key'
      AWS_SECRET_ACCESS_KEY: 'secret'
      S3_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 1234:1234
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      CI_URL: ''
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api`
```
tests run sequentually. Seems that the keywork --parallel doesn't work.
